services:
  postgres:
    image: postgres:16-alpine
    container_name: flp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ferreteria_los_puentes
    ports:
      - "5432:5432"
    volumes:
      - flp_postgres_data:/var/lib/postgresql/data

volumes:
  flp_postgres_data:
