/**
 * Definición de permisos y roles del sistema RBAC
 */

export const PERMISSIONS = {
  CONFIG_VIEW: 'CONFIG_VIEW',
  CONFIG_MANAGE: 'CONFIG_MANAGE',
  BANKS_VIEW: 'BANKS_VIEW',
  BANKS_MANAGE: 'BANKS_MANAGE',
  PAYMENT_METHODS_MANAGE: 'PAYMENT_METHODS_MANAGE',
  EXCHANGE_RATE_VIEW: 'EXCHANGE_RATE_VIEW',
  EXCHANGE_RATE_MANAGE: 'EXCHANGE_RATE_MANAGE',

  PRODUCTS_VIEW: 'PRODUCTS_VIEW',
  PRODUCTS_MANAGE: 'PRODUCTS_MANAGE',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_SHRINKAGE: 'INVENTORY_SHRINKAGE',

  SUPPLIERS_VIEW: 'SUPPLIERS_VIEW',
  SUPPLIERS_MANAGE: 'SUPPLIERS_MANAGE',
  PURCHASES_VIEW: 'PURCHASES_VIEW',
  PURCHASES_CREATE: 'PURCHASES_CREATE',
  PURCHASES_APPROVE: 'PURCHASES_APPROVE',
  ACCOUNTS_PAYABLE_VIEW: 'ACCOUNTS_PAYABLE_VIEW',
  ACCOUNTS_PAYABLE_MANAGE: 'ACCOUNTS_PAYABLE_MANAGE',

  CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
  CUSTOMERS_MANAGE: 'CUSTOMERS_MANAGE',
  INVOICES_VIEW: 'INVOICES_VIEW',
  INVOICES_CREATE: 'INVOICES_CREATE',
  INVOICES_VOID: 'INVOICES_VOID',
  CREDIT_NOTES_CREATE: 'CREDIT_NOTES_CREATE',
  DEBIT_NOTES_CREATE: 'DEBIT_NOTES_CREATE',
  ACCOUNTS_RECEIVABLE_VIEW: 'ACCOUNTS_RECEIVABLE_VIEW',
  ACCOUNTS_RECEIVABLE_MANAGE: 'ACCOUNTS_RECEIVABLE_MANAGE',

  POS_ACCESS: 'POS_ACCESS',
  POS_SELL: 'POS_SELL',
  POS_HOLD: 'POS_HOLD',
  POS_PRICE_LOOKUP: 'POS_PRICE_LOOKUP',
  CASH_REGISTER_OPEN: 'CASH_REGISTER_OPEN',
  CASH_REGISTER_CLOSE: 'CASH_REGISTER_CLOSE',
  CASH_REGISTER_VIEW: 'CASH_REGISTER_VIEW',

  REPORTS_DAILY_SALES: 'REPORTS_DAILY_SALES',
  REPORTS_SALES_BOOK: 'REPORTS_SALES_BOOK',
  REPORTS_INVENTORY_ANALYSIS: 'REPORTS_INVENTORY_ANALYSIS',
  REPORTS_CASH_FLOW: 'REPORTS_CASH_FLOW',
  REPORTS_EXPORT: 'REPORTS_EXPORT',

  USERS_VIEW: 'USERS_VIEW',
  USERS_MANAGE: 'USERS_MANAGE',
  ROLES_MANAGE: 'ROLES_MANAGE',

  BRANCHES_VIEW: 'BRANCHES_VIEW',
  BRANCHES_MANAGE: 'BRANCHES_MANAGE',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  ADMIN: 'ADMIN',
  ADMIN_OPERATOR: 'ADMIN_OPERATOR',
  CASHIER: 'CASHIER',
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];

/** Permisos asignados por defecto a cada rol del sistema */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN_OPERATOR]: [
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.BANKS_VIEW,
    PERMISSIONS.EXCHANGE_RATE_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.ACCOUNTS_PAYABLE_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.CREDIT_NOTES_CREATE,
    PERMISSIONS.ACCOUNTS_RECEIVABLE_VIEW,
    PERMISSIONS.REPORTS_DAILY_SALES,
    PERMISSIONS.REPORTS_SALES_BOOK,
    PERMISSIONS.REPORTS_INVENTORY_ANALYSIS,
    PERMISSIONS.CASH_REGISTER_VIEW,
  ],

  [ROLES.CASHIER]: [
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_SELL,
    PERMISSIONS.POS_HOLD,
    PERMISSIONS.POS_PRICE_LOOKUP,
    PERMISSIONS.CASH_REGISTER_OPEN,
    PERMISSIONS.CASH_REGISTER_CLOSE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.EXCHANGE_RATE_VIEW,
  ],
};

/** Verifica si un conjunto de permisos del usuario satisface los requeridos */
export function hasPermission(
  userPermissions: PermissionCode[],
  required: PermissionCode | PermissionCode[],
): boolean {
  const requiredList = Array.isArray(required) ? required : [required];
  return requiredList.every((p) => userPermissions.includes(p));
}

/** Verifica si el usuario tiene al menos uno de los permisos requeridos */
export function hasAnyPermission(
  userPermissions: PermissionCode[],
  required: PermissionCode[],
): boolean {
  return required.some((p) => userPermissions.includes(p));
}

/** Verifica si el usuario tiene todos los permisos requeridos */
export function hasAllPermissions(
  userPermissions: PermissionCode[],
  required: PermissionCode[],
): boolean {
  return required.every((p) => userPermissions.includes(p));
}
